name: wuxia_crowler
description: My personal book reader.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_search_bar: ^2.1.0
  http: 0.12.2
  flutter_tts: 1.0.0
  page_turn: ^1.0.1
  quiver: ^2.1.5

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true